<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebApplicationWeb._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <script src="Default.js<%--?ver<%=DateTime.Now.Ticks.ToString()%>--%>" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <div class ="container">
        <h2> User Information Management</h2>
        
      <form id="mainForm" class="form-horizontal" method="post" target="" enctype="multipart/form-data">
      <div class="form-group">
          <div class="row">
       <label for="name" class="form-label">Name:</label>
       <input type="text" class="form-control" id="username" name ="username" placeholder="請輸入人員的名子">
              </div>
    </div>
    <div class="form-group">
        <div class="row">
       <label for="age" class="form-label">Age:</label>
       <input type="text" class="form-control" id="age" name="age" placeholder="請輸入人員的年齡">
            </div>
    </div>
    <div class="form-group">
        <div class="row">
       <label for="birthday" class="form-label">Birthday:</label>
       <input type="date" class="form-control" id="birthday" name="birthday" placeholder="請輸入人員的生日">
            </div>
    </div>
          <div class="form-group">        
      <div class="row">
          
          <asp:Button ID="Button1" runat="server" OnClick="AddBtn_Click" Text="Add User" Width="150px" />
          </form>
          <br/>
          <br/>
          <asp:GridView ID="GridView1" runat="server" 
  AutoGenerateDeleteButton="True" 
  AutoGenerateEditButton="True" 
  DataKeyNames="id" 
  onrowdeleting="GridView1_RowDeleting" 
  onrowediting="GridView1_RowEditing" 
  onrowupdating="GridView1_RowUpdating" 
  onrowcancelingedit="GridView1_RowCancelingEdit"  Width="516px" Height="144px" >
          </asp:GridView>
          <br />
          <br />
          <br />
          
          <br />
          <br />
      </div>
    </div>
        
        </div>

    <%--<div class ="container">
            <table id="TABLE1" class="table table-bordered table-striped" cellpadding="0" cellspacing="5">
                <thead class="thead-dark">
                    <tr>
                        <th>姓名</th>
                        <th>年齡</th>
                        <th>生日</th>
                        <th>#</th>

                    </tr>
                    <thead>
                        <tbody>
                    
                            </tbody>
                    
            </table>
        </div>--%>
   
</asp:Content>

